FROM node:alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package.json .
#RUN npm install
RUN yarn && yarn cache clean

# Bundle app source
COPY . .

# Exports
#EXPOSE 3000
CMD [ "npm", "run", "dev" ]