version: '3'

services:
  app:
    env_file: 
      - ./config/dev.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: nodemon -e js,hbs app.js
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "3000:3000"


  test:
    env_file: 
      - ./config/test.env 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    #environment: 
      #- CI=true
    command: npm test
  